project_name: "db-migrate-name"
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/db-migrate-name
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
